---
title: "Data Import Practice"
author: "Caroline Andy"
date: "9/22/2020"
output: html_document
---
Reading in example dataset provided from class links
```{r readr}
library(tidyverse)
litters_data = read_csv(file = "./data_import_examples/FAS_litters.csv")
```

Now I will view column names and clean using Janitor
```{r janitor}
names(litters_data)
litters_data <- janitor::clean_names(litters_data)
names(litters_data)
```

Here's a really awesome way to get a bunch of cool summary stats:
```{r skim}
skimr::skim(litters_data)
```

If I want to change all of my variable types I can do so as follows:
```{r skim}
litters_data = read_csv(file = "./data_import_examples/FAS_litters.csv",
  col_types = cols(
    Group = col_character(),
    `Litter Number` = col_character(),
    `GD0 weight` = col_double(),
    `GD18 weight` = col_double(),
    `GD of Birth` = col_integer(),
    `Pups born alive` = col_integer(),
    `Pups dead @ birth` = col_integer(),
    `Pups survive` = col_integer()
  )
)
#Here is a short hand:
litters_data = read_csv(file = "./data_import_examples/FAS_litters.csv",
  col_types = "ccddiiii"
)
```
